// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type KeyTermsClassView struct {
	inner baml.ClassBuilder
}

func (t *KeyTermsClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *KeyTermsClassView) PropertyTechnical_skills() (ClassPropertyView, error) {
	return t.inner.Property("technical_skills")
}

func (t *KeyTermsClassView) PropertySoft_skills() (ClassPropertyView, error) {
	return t.inner.Property("soft_skills")
}

func (t *KeyTermsClassView) PropertyRequirements() (ClassPropertyView, error) {
	return t.inner.Property("requirements")
}

func (t *KeyTermsClassView) PropertyNice_to_have() (ClassPropertyView, error) {
	return t.inner.Property("nice_to_have")
}

func (t *TypeBuilder) KeyTerms() (*KeyTermsClassView, error) {
	bld, err := t.inner.Class("KeyTerms")
	if err != nil {
		return nil, err
	}
	return &KeyTermsClassView{inner: bld}, nil
}

func (t *KeyTermsClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type TweakAnalysisClassView struct {
	inner baml.ClassBuilder
}

func (t *TweakAnalysisClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *TweakAnalysisClassView) PropertySummary() (ClassPropertyView, error) {
	return t.inner.Property("summary")
}

func (t *TweakAnalysisClassView) PropertyKeywords_added() (ClassPropertyView, error) {
	return t.inner.Property("keywords_added")
}

func (t *TweakAnalysisClassView) PropertySections_improved() (ClassPropertyView, error) {
	return t.inner.Property("sections_improved")
}

func (t *TweakAnalysisClassView) PropertyMatch_score() (ClassPropertyView, error) {
	return t.inner.Property("match_score")
}

func (t *TypeBuilder) TweakAnalysis() (*TweakAnalysisClassView, error) {
	bld, err := t.inner.Class("TweakAnalysis")
	if err != nil {
		return nil, err
	}
	return &TweakAnalysisClassView{inner: bld}, nil
}

func (t *TweakAnalysisClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}
