// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/johnhkchen/resume-tweaker/baml_client/baml_client/types"
)

func AnalyzeTweak(ctx context.Context, original_resume string, tweaked_resume string, job_description string, opts ...CallOptionFunc) (types.TweakAnalysis, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"original_resume": original_resume, "tweaked_resume": tweaked_resume, "job_description": job_description},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "AnalyzeTweak", encoded, callOpts.onTick)
		if err != nil {
			return types.TweakAnalysis{}, err
		}

		if result.Error != nil {
			return types.TweakAnalysis{}, result.Error
		}

		casted := (result.Data).(types.TweakAnalysis)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "AnalyzeTweak", encoded, callOpts.onTick)
		if err != nil {
			return types.TweakAnalysis{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.TweakAnalysis{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.TweakAnalysis), nil
			}
		}

		return types.TweakAnalysis{}, fmt.Errorf("No data returned from stream")
	}
}

func ExtractJobKeyTerms(ctx context.Context, job_description string, opts ...CallOptionFunc) (types.KeyTerms, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"job_description": job_description},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "ExtractJobKeyTerms", encoded, callOpts.onTick)
		if err != nil {
			return types.KeyTerms{}, err
		}

		if result.Error != nil {
			return types.KeyTerms{}, result.Error
		}

		casted := (result.Data).(types.KeyTerms)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "ExtractJobKeyTerms", encoded, callOpts.onTick)
		if err != nil {
			return types.KeyTerms{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.KeyTerms{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.KeyTerms), nil
			}
		}

		return types.KeyTerms{}, fmt.Errorf("No data returned from stream")
	}
}

func TweakResume(ctx context.Context, resume string, job_description string, opts ...CallOptionFunc) (string, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"resume": resume, "job_description": job_description},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "TweakResume", encoded, callOpts.onTick)
		if err != nil {
			return "", err
		}

		if result.Error != nil {
			return "", result.Error
		}

		casted := (result.Data).(string)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "TweakResume", encoded, callOpts.onTick)
		if err != nil {
			return "", err
		}

		for result := range channel {
			if result.Error != nil {
				return "", result.Error
			}

			if result.HasData {
				return result.Data.(string), nil
			}
		}

		return "", fmt.Errorf("No data returned from stream")
	}
}
