// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"reflect"

	"github.com/johnhkchen/resume-tweaker/baml_client/baml_client/stream_types"
	"github.com/johnhkchen/resume-tweaker/baml_client/baml_client/types"
)

var typeMap = map[string]reflect.Type{
	"TYPES.KeyTerms":             reflect.TypeOf(types.KeyTerms{}),
	"STREAM_TYPES.KeyTerms":      reflect.TypeOf(stream_types.KeyTerms{}),
	"TYPES.TweakAnalysis":        reflect.TypeOf(types.TweakAnalysis{}),
	"STREAM_TYPES.TweakAnalysis": reflect.TypeOf(stream_types.TweakAnalysis{}),
}
