// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Landing() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"max-w-4xl mx-auto px-6 py-16\"><div class=\"text-center space-y-6\"><h1 class=\"text-4xl font-bold tracking-tight\">Tailor Your Resume to Any Job</h1><p class=\"text-xl text-muted-foreground max-w-2xl mx-auto\">Paste your resume and a job description. Watch as AI suggests improvements in real-time.</p><div class=\"pt-4\"><a href=\"/tweak\" class=\"inline-flex items-center justify-center px-8 py-3 text-lg font-medium rounded-lg bg-primary text-primary-foreground hover:bg-primary/90 transition-colors\">Start Tweaking</a></div></div><div class=\"mt-20 grid md:grid-cols-3 gap-8\"><div class=\"space-y-3\"><div class=\"h-12 w-12 rounded-lg bg-muted flex items-center justify-center text-2xl\">1</div><h3 class=\"text-lg font-semibold\">Paste Your Resume</h3><p class=\"text-muted-foreground\">Copy and paste your current resume into the editor.</p></div><div class=\"space-y-3\"><div class=\"h-12 w-12 rounded-lg bg-muted flex items-center justify-center text-2xl\">2</div><h3 class=\"text-lg font-semibold\">Add Job Description</h3><p class=\"text-muted-foreground\">Paste the job description you're targeting.</p></div><div class=\"space-y-3\"><div class=\"h-12 w-12 rounded-lg bg-muted flex items-center justify-center text-2xl\">3</div><h3 class=\"text-lg font-semibold\">Get Improvements</h3><p class=\"text-muted-foreground\">Watch AI suggestions stream in real-time.</p></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Home").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
