// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package stream_types

import (
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)

type KeyTerms struct {
	Technical_skills []string `json:"technical_skills"`
	Soft_skills      []string `json:"soft_skills"`
	Requirements     []string `json:"requirements"`
	Nice_to_have     []string `json:"nice_to_have"`
}

func (c *KeyTerms) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "KeyTerms" {
		panic(fmt.Sprintf("expected KeyTerms, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "technical_skills":
			c.Technical_skills = baml.Decode(valueHolder).Interface().([]string)

		case "soft_skills":
			c.Soft_skills = baml.Decode(valueHolder).Interface().([]string)

		case "requirements":
			c.Requirements = baml.Decode(valueHolder).Interface().([]string)

		case "nice_to_have":
			c.Nice_to_have = baml.Decode(valueHolder).Interface().([]string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class KeyTerms", key))

		}
	}

}

func (c KeyTerms) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["technical_skills"] = c.Technical_skills

	fields["soft_skills"] = c.Soft_skills

	fields["requirements"] = c.Requirements

	fields["nice_to_have"] = c.Nice_to_have

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c KeyTerms) BamlTypeName() string {
	return "KeyTerms"
}

func (u KeyTerms) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_STREAM_TYPES,
		Name:      "KeyTerms",
	}
}

type TweakAnalysis struct {
	Summary           *string  `json:"summary"`
	Keywords_added    []string `json:"keywords_added"`
	Sections_improved []string `json:"sections_improved"`
	Match_score       *int64   `json:"match_score"`
}

func (c *TweakAnalysis) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "TweakAnalysis" {
		panic(fmt.Sprintf("expected TweakAnalysis, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "summary":
			c.Summary = baml.Decode(valueHolder).Interface().(*string)

		case "keywords_added":
			c.Keywords_added = baml.Decode(valueHolder).Interface().([]string)

		case "sections_improved":
			c.Sections_improved = baml.Decode(valueHolder).Interface().([]string)

		case "match_score":
			c.Match_score = baml.Decode(valueHolder).Interface().(*int64)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class TweakAnalysis", key))

		}
	}

}

func (c TweakAnalysis) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["summary"] = c.Summary

	fields["keywords_added"] = c.Keywords_added

	fields["sections_improved"] = c.Sections_improved

	fields["match_score"] = c.Match_score

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c TweakAnalysis) BamlTypeName() string {
	return "TweakAnalysis"
}

func (u TweakAnalysis) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_STREAM_TYPES,
		Name:      "TweakAnalysis",
	}
}
